services:
  auth-service:
    build: ./auth-service
    ports:
      - "3004:3004"
    env_file:
      - ./auth-service/.env
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: crystal-event
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
